# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-15 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0016_auto_20190818_1347'),
        ('livestream', '0002_auto_20190907_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twiliorooms', to='catalogue.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioRoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='twilioroom',
            name='twilio_room_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twiliorooms', to='livestream.TwilioRoomStatus'),
        ),
    ]
