version: '2'

services:    
    sosci:
          # build looks for a dockerfile in a specified location
          build: .
          restart: always
          expose:
            - "8000"
          links:
            - postgres:postgres
          env_file: ./.env
          volumes:
             - . :/data/sosci
          command: /usr/bin/gunicorn sosci.wsgi:application -w 2 -b :8000
          depends_on:
                    - postgres
    nginx:
          restart: always
          build: ./config/docker/nginx
          ports:
            - "80:80"
          volumes_from:
            - sosci
          links:
            - sosci:sosci
          depends_on:
                    - sosci            
    postgres:
      restart: always
      image: postgres:latest
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./volumes/backups/postgresql:/backup
      env_file:
        - ./.env
      expose:
        - "5432"

volumes:
  pgdata:
     external: true                                                     