# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-22 03:45
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

def forward(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    pk = settings.SITE_ID or 1
    site, created = Site.objects.using(db_alias).get_or_create(pk=pk)
    site.name = settings.SITE_NAME or "sosci"
    site.domain = settings.SITE_DOMAIN or "sosci.herokuapp.com"
    site.save()


def reverse(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    pk = settings.SITE_ID or 1
    site = Site.objects.using(db_alias).get(pk=pk)
    site.name = "sosci"
    site.domain = "sosci.herokuapp.com"
    site.save()


class Migration(migrations.Migration):

    dependencies = [

        # `0002_alter_domain_unique` is the highest-numbered migration for
        # the sites framework
        ('sites', '0002_alter_domain_unique'),

    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
