# Generated by Django 2.2.9 on 2019-12-27 23:10

import customer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20191223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationeventtype',
            name='code',
            field=customer.fields.AutoSlugField(allow_duplicates='"\'False\'"', blank=True, editable=False, help_text='Code used for looking up this event programmatically', max_length=128, overwrite='"\'False\'"', populate_from='\'"\\\'name\\\'"\'', separator='\'"\\\'_\\\'"\'', unique=True, verbose_name='Code'),
        ),
    ]
