# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_seen'),
        ('course', '0002_auto_20190616_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursemodules', to='video.Video'),
        ),
    ]
