# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-07 22:21
from __future__ import unicode_literals

import customer.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_email_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationeventtype',
            name='category',
            field=models.CharField(default='User related', max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='communicationeventtype',
            name='code',
            field=customer.fields.AutoSlugField(allow_duplicates=b'"\'False\'"', blank=True, editable=False, help_text='Code used for looking up this event programmatically', max_length=128, overwrite=b'"\'False\'"', populate_from=b'\'"\\\'name\\\'"\'', separator=b'\'"\\\'_\\\'"\'', unique=True, verbose_name='Code'),
        ),
    ]
