# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-17 20:29
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    UserRole = apps.get_model("custom_user", "UserRole")
    db_alias = schema_editor.connection.alias
    UserRole.objects.using(db_alias).bulk_create([
        UserRole(name="Instructor"),
        UserRole(name="Student"),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    UserRole = apps.get_model("custom_user", "UserRole")
    db_alias = schema_editor.connection.alias
    UserRole.objects.using(db_alias).filter(name="Instructor").delete()
    UserRole.objects.using(db_alias).filter(name="Student").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20191117_1457'),
    ]

    operations = [
     migrations.RunPython(forwards_func, reverse_func),
    ]
