# Generated by Django 2.2.9 on 2019-12-29 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_auto_20191227_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2019, 12, 28)),
        ),
    ]
