# Generated by Django 2.2.9 on 2020-01-12 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_auto_20191228_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2020, 1, 12)),
        ),
    ]
