# Generated by Django 2.2.9 on 2020-01-15 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_auto_20200112_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2020, 1, 14)),
        ),
    ]
