# Generated by Django 2.2.9 on 2020-03-01 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_auto_20200114_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2020, 3, 1)),
        ),
    ]
