# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_coursemodule_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodule',
            old_name='course',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='course',
            new_name='product',
        ),
    ]
