# Generated by Django 2.2.9 on 2020-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20200112_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
