# Generated by Django 2.2.9 on 2020-01-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_product_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
