# Generated by Django 2.2.9 on 2020-03-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20200114_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='duration',
        ),
    ]
