# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.CharField(blank=True, help_text='a url pointing directly to a preview image of the first video in a course', max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('video_id', models.IntegerField()),
                ('width', models.IntegerField(default=800)),
                ('height', models.IntegerField(default=480)),
                ('duration', models.DecimalField(decimal_places=2, default=0, help_text='duration of the video', max_digits=64)),
                ('picture', models.CharField(blank=True, help_text='a url pointing directly to a preview image of the video', max_length=250, null=True)),
                ('upload_link', models.CharField(blank=True, help_text='a link that points directly to the video on the vimeo server', max_length=250, null=True)),
                ('upload_status', models.CharField(blank=True, help_text='the upload status of the video. possible values are: in_progress, complete, error', max_length=11, null=True)),
                ('transcode_status', models.CharField(blank=True, help_text='the transcoding status of the video. possible values are: in_progress, complete, error', max_length=11, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.Course')),
            ],
        ),
    ]
