# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190615_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='seen',
            field=models.BooleanField(default=False, help_text='determines whether a video has been watched or not'),
        ),
    ]
