# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190804_1410'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursemodules', to='video.Video'),
        ),
    ]
