# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_coursemodule_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='video',
        ),
    ]
