# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-21 23:32
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ProductClass = apps.get_model("catalogue", "ProductClass")
    db_alias = schema_editor.connection.alias
    ProductClass.objects.using(db_alias).bulk_create([
        ProductClass(name="Course",slug="course",requires_shipping=False,track_stock=False),
        ProductClass(name="Live",slug="live",requires_shipping=False,track_stock=False)
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    ProductClass = apps.get_model("catalogue", "ProductClass")
    db_alias = schema_editor.connection.alias
    ProductClass.objects.using(db_alias).filter(name="Course").delete()
    ProductClass.objects.using(db_alias).filter(name="Live").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_is_published'),
    ]

    operations = [
    migrations.RunPython(forwards_func, reverse_func),
    ]
